# Generated by Django 5.2.9 on 2026-03-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_remove_privatelessonorder_private_lesson_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_link_send",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="course",
            name="type",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("offline", "Offline"),
                    ("private", "Private"),
                ],
                default="online",
                max_length=10,
            ),
        ),
    ]
