# Generated by Django 5.2.9 on 2026-03-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_course_is_link_send_alter_course_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseorder",
            name="is_link_send",
            field=models.BooleanField(default=False),
        ),
    ]
