# Generated by Django 5.2.9 on 2026-03-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_supportmodel_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportmodel",
            name="is_phone",
            field=models.BooleanField(default=False),
        ),
    ]
