# Generated by Django 5.2.9 on 2026-03-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_digitalproductorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalproductorder",
            name="is_link_send",
            field=models.BooleanField(default=False),
        ),
    ]
