# Generated by Django 5.2.9 on 2026-03-14 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_category_created_at_tag_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseFeaturesImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.JSONField(blank=True, default=list)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CourseGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("image_public_id", models.CharField(max_length=255)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WebPageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "logo_public_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hero_title_first",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hero_title_second",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hero_title_third",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WebPageHeroImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("image_public_id", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "webpage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_images",
                        to="blog.webpagemodel",
                    ),
                ),
            ],
        ),
    ]
