# Generated by Django 5.2.9 on 2026-03-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_coursefeaturesimage_coursegalleryimage_webpagemodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpagemodel",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
