# Generated by Django 5.2.9 on 2026-03-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_webpagemodel_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseFeaturesImage",
        ),
    ]
