# Generated by Django 5.2.9 on 2026-03-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_delete_coursefeaturesimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("image_public_id", models.CharField(max_length=255)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
